# ----
# Site

title: S5platform
url: "https://s5platform.github.io"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: documentation template for S5platform.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: S5platform
  links:
    - https://s5platform.github.io

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation


# -----------
# CloudCannon

types:
  - minor
  - major
